import os

import pyodbc
 
DB_CONFIG = {

    'SQL_SERVER': 'SRVWUDEN0890V',

    'SQL_DB': 'ACVSCore',

    'SQL_USER': 'GSOC_Test',

    'SQL_PASSWORD': 'Westerngsoc@2025',

    'trusted_connection': False

}
 
FILE_PATHS = {

    'excel_file_1': r"C:\Users\W0019058\OneDrive - Western Union\Desktop\CCURE-Comparison\data\Active Contractors Sheet.xls",

    'excel_file_2': r"C:\Users\W0019058\OneDrive - Western Union\Desktop\CCURE-Comparison\data\Active Employees sheet.xlsx",

    'output_report': r"C:\Users\W0019058\OneDrive - Western Union\Desktop\CCURE-Comparison\data\comparison_report.xlsx"

}
 
def get_sql_connection(SQL_SERVER, SQL_DB, SQL_USER, SQL_PASSWORD):

    try:

        return pyodbc.connect(

            f"DRIVER={{ODBC Driver 17 for SQL Server}};"

            f"SERVER={SQL_SERVER};DATABASE={SQL_DB};UID={SQL_USER};PWD={SQL_PASSWORD}"

        )

    except Exception as e:

        print(f"Connection error for server {SQL_SERVER}: {e}")

        return None
 
def build_sql_query():

    return """

      SELECT DISTINCT
    AP.ObjectID AS "AccountName",
    AP.Name AS "Emp Name",
	CASE AP.Int1
        WHEN 0 THEN AP.Text12
        ELSE CAST(AP.Int1 AS NVARCHAR)
    END AS "EmployeeID",
	AP.text9 AS Temp_Badge_No,
    PT.Name AS "PersonnelType",
	Text10 AS Manager_Name,
	Int4 As Manager_WU_ID
FROM
    ACVSCore.Access.Personnel AP
    Full JOIN ACVSCore.Access.Credential ACR ON AP.Name = ACR.Name
    Full JOIN ACVSCore.Access.PersonnelType PT ON PT.ObjectID = AP.PersonnelTypeID
WHERE
    AP.Disabled = 0
ORDER BY
    "AccountName" ASC;

    """
 
def check_alerts_for_server(server_config):

    print("ENTERED check_alert function")

    conn = get_sql_connection(server_config['SQL_SERVER'], server_config['SQL_DB'], server_config['SQL_USER'], server_config['SQL_PASSWORD'])

    if not conn:

        return

    try:

        cursor = conn.cursor()

        cursor.execute(build_sql_query())
 
        rows = cursor.fetchall()

        if not rows:

            print("No new alerts")

            return
 
        columns = [desc[0] for desc in cursor.description]
 
        for row in rows:

            data = dict(zip(columns, row))

            print(data)
 
    except Exception as e:

        print(f"Error executing sql query: {e}")
 
    finally:

        conn.close()
 
# Call the function to test

check_alerts_for_server(DB_CONFIG)


Traceback (most recent call last):
  File "C:\Users\W0019058\OneDrive - Western Union\Desktop\CCURE-Comparison\.venv\Lib\site-packages\pandas\core\indexes\base.py", line 3812, in get_loc
    return self._engine.get_loc(casted_key)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "pandas/_libs/index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7096, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'W iPass ID'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\W0019058\OneDrive - Western Union\Desktop\CCURE-Comparison\scripts\compare_profiles.py", line 83, in <module>
    run_comparison()
    ~~~~~~~~~~~~~~^^
  File "C:\Users\W0019058\OneDrive - Western Union\Desktop\CCURE-Comparison\scripts\compare_profiles.py", line 74, in run_comparison
    all_excel_ids = prepare_id_sets(contractors_df, employees_df)
  File "C:\Users\W0019058\OneDrive - Western Union\Desktop\CCURE-Comparison\scripts\compare_profiles.py", line 37, in prepare_id_sets
    contractors_df['W iPass ID'].astype(str)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\W0019058\OneDrive - Western Union\Desktop\CCURE-Comparison\.venv\Lib\site-packages\pandas\core\frame.py", line 4107, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\Users\W0019058\OneDrive - Western Union\Desktop\CCURE-Comparison\.venv\Lib\site-packages\pandas\core\indexes\base.py", line 3819, in get_loc
    raise KeyError(key) from err
KeyError: 'W iPass ID'
